/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 *
 * @preserve
 **/

 (function ($, Drupal) {
    Drupal.behaviors.banner = {
        attach: function attach(context)
        {
            // On Load hide extra slides.
            jQuery(".slide-show").hide();
            var no_of_slide = jQuery("#no_of_slide").val();
            for (let i = 1; i <= no_of_slide; i++) {
                jQuery("#slide"+i).show();
            }
            jQuery("#no_of_slide").change(
                function () {
                    jQuery(".slide-show").hide();
                    var no_of_slide = jQuery("#no_of_slide").val();
                    for (let i = 1; i <= no_of_slide; i++) {
                        jQuery("#slide"+i).show();
                    }
                }
            );      
        }
    };
})(jQuery, Drupal);
